const data = {
  products: [
    {
      name: 'Nike ',
      slug: 'nike-slim-trouser',
      category: 'trouser',
      image: '/images/image1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality trouser',
    },
    {
      name: 'Addidas ',
      slug: 'Addidas-slim-trouser',
      category: 'trouser',
      image: '/images/image2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality trouser',
    },
    {
      name: 'Lacoste slim trouser',
      slug: 'Lacoste-slim-trouser',
      category: 'trousers',
      image: '/images/image3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality trouser',
    },
    {
      name: 'Givenchy slim trouser',
      slug: 'givenchy-slim-trouser',
      category: 'Trousers',
      image: '/images/image4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Givenchy',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality trouser',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/image5.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Addidas ',
      slug: 'addidas-slim-shirt',
      category: 'shirts',
      image: '/images/mage6.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Lacoste slim shirt',
      slug: 'lacoste-slim-shirt',
      category: 'shirts',
      image: '/images/image7.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Palm angels slim shirt',
      slug: 'palm-angel-slim-shirt',
      category: 'shirts',
      image: '/images/image8.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Palm angel',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Renato slim shirt',
      slug: 'renato-slim-shirt',
      category: 'shirts',
      image: '/images/image9.jpg', //679px x 829px
      price: 120,
      countInStock: 10,
      brand: 'Renato',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};

export default data;
